"""add pnl_start_date, product currency_id, currency_rates

Revision ID: 12a1fa4d0974
Revises: 5cc3d820c565
Create Date: 2026-09-01 12:50:48.273093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a1fa4d0974'
down_revision: Union[str, Sequence[str], None] = '5cc3d820c565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('rate_date', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'rate_date', name='unique_currency_rate_day')
    )
    op.create_index(op.f('ix_currency_rates_currency_id'), 'currency_rates', ['currency_id'], unique=False)
    op.create_index(op.f('ix_currency_rates_id'), 'currency_rates', ['id'], unique=False)
    op.create_index(op.f('ix_currency_rates_rate_date'), 'currency_rates', ['rate_date'], unique=False)
    op.add_column('accounts', sa.Column('pnl_start_date', sa.String(), nullable=True))
    op.add_column('products', sa.Column('currency_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency_id')
    op.drop_column('accounts', 'pnl_start_date')
    op.drop_index(op.f('ix_currency_rates_rate_date'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_id'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_currency_id'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
