"""add daily_pnl_snapshots table

Revision ID: 31b7f61e3d9c
Revises: d3fbac761bb6
Create Date: 2026-09-01 22:10:27.044483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b7f61e3d9c'
down_revision: Union[str, Sequence[str], None] = 'd3fbac761bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
