"""add alert_settings and alert_emails tables

Revision ID: 3dc6ebf3f2ee
Revises: f65d8207f6c0
Create Date: 2026-09-03 07:50:01.912224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc6ebf3f2ee'
down_revision: Union[str, Sequence[str], None] = 'f65d8207f6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
