"""baseline schema

Revision ID: 5cc3d820c565
Revises: 
Create Date: 2026-08-31 22:11:40.577661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc3d820c565'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tt_account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_account_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_index(op.f('ix_accounts_tt_account_id'), 'accounts', ['tt_account_id'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tt_market_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_index(op.f('ix_markets_name'), 'markets', ['name'], unique=True)
    op.create_index(op.f('ix_markets_tt_market_id'), 'markets', ['tt_market_id'], unique=True)
    op.create_table('products',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('displayFactor', sa.Integer(), nullable=True),
    sa.Column('displayType', sa.Integer(), nullable=True),
    sa.Column('expirationDate', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('lastTradeDate', sa.BigInteger(), nullable=True),
    sa.Column('marketId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pointValue', sa.Float(), nullable=True),
    sa.Column('productFamilyId', sa.String(), nullable=True),
    sa.Column('productId', sa.String(), nullable=True),
    sa.Column('productSymbol', sa.String(), nullable=True),
    sa.Column('productTypeId', sa.Integer(), nullable=True),
    sa.Column('ricCode', sa.String(), nullable=True),
    sa.Column('roundLotQty', sa.Integer(), nullable=True),
    sa.Column('securityExchange', sa.Integer(), nullable=True),
    sa.Column('securityId', sa.String(), nullable=True),
    sa.Column('seriesTermId', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('tickSize', sa.Float(), nullable=True),
    sa.Column('tickSizeDenominator', sa.Integer(), nullable=True),
    sa.Column('tickSizeNumerator', sa.Integer(), nullable=True),
    sa.Column('tickValue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('db_id')
    )
    op.create_index(op.f('ix_products_db_id'), 'products', ['db_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('account_product_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('product_symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'product_symbol', name='unique_account_product')
    )
    op.create_index(op.f('ix_account_product_settings_id'), 'account_product_settings', ['id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('tt_account_id', sa.BigInteger(), nullable=False),
    sa.Column('aggressor_indicator', sa.String(), nullable=True),
    sa.Column('algo_id', sa.BigInteger(), nullable=True),
    sa.Column('alloc_id', sa.String(), nullable=True),
    sa.Column('avg_px', sa.Float(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('cum_qty', sa.Float(), nullable=True),
    sa.Column('curr_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delta_qty', sa.Float(), nullable=True),
    sa.Column('exch_leaves_qty', sa.Float(), nullable=True),
    sa.Column('exch_order_assoc', sa.String(), nullable=True),
    sa.Column('exec_id', sa.String(), nullable=False),
    sa.Column('exec_inst', sa.Integer(), nullable=True),
    sa.Column('exec_type', sa.Integer(), nullable=True),
    sa.Column('externally_created', sa.String(), nullable=True),
    sa.Column('handling_instr', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('last_px', sa.Float(), nullable=False),
    sa.Column('last_qty', sa.Float(), nullable=False),
    sa.Column('manual_fill', sa.Boolean(), nullable=True),
    sa.Column('manual_order_indicator', sa.Boolean(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Integer(), nullable=True),
    sa.Column('multi_leg_reporting_type', sa.String(), nullable=True),
    sa.Column('ord_status', sa.String(), nullable=True),
    sa.Column('ord_type', sa.Integer(), nullable=True),
    sa.Column('order_cross_prevention_type', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('parent_instrument_id', sa.String(), nullable=True),
    sa.Column('parent_order_id', sa.String(), nullable=True),
    sa.Column('position_effect', sa.String(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('secondary_cl_ord_id', sa.String(), nullable=True),
    sa.Column('secondary_exec_id', sa.String(), nullable=True),
    sa.Column('secondary_order_id', sa.String(), nullable=True),
    sa.Column('security_desc', sa.String(), nullable=True),
    sa.Column('sender_location_id', sa.String(), nullable=True),
    sa.Column('sender_sub_id', sa.String(), nullable=True),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('synthetic_type', sa.Integer(), nullable=True),
    sa.Column('text_a', sa.String(), nullable=True),
    sa.Column('text_b', sa.String(), nullable=True),
    sa.Column('text_c', sa.String(), nullable=True),
    sa.Column('text_tt', sa.String(), nullable=True),
    sa.Column('time_in_force', sa.Integer(), nullable=True),
    sa.Column('time_sent_client', sa.String(), nullable=True),
    sa.Column('time_sent_tt', sa.String(), nullable=True),
    sa.Column('time_stamp', sa.String(), nullable=True),
    sa.Column('trade_date', sa.String(), nullable=True),
    sa.Column('trade_match_id', sa.String(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=True),
    sa.Column('trading_venue_trade_id', sa.String(), nullable=True),
    sa.Column('transact_time', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Integer(), nullable=True),
    sa.Column('unique_exec_id', sa.String(), nullable=True),
    sa.Column('fills_group', sa.JSON(), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=True),
    sa.Column('report_sides', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_account_id'), 'fills', ['account_id'], unique=False)
    op.create_index(op.f('ix_fills_account_name'), 'fills', ['account_name'], unique=False)
    op.create_index(op.f('ix_fills_exec_id'), 'fills', ['exec_id'], unique=True)
    op.create_index(op.f('ix_fills_id'), 'fills', ['id'], unique=False)
    op.create_index(op.f('ix_fills_instrument_id'), 'fills', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_fills_market_id'), 'fills', ['market_id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_record_id'), 'fills', ['record_id'], unique=True)
    op.create_index(op.f('ix_fills_security_desc'), 'fills', ['security_desc'], unique=False)
    op.create_index(op.f('ix_fills_trade_date'), 'fills', ['trade_date'], unique=False)
    op.create_index(op.f('ix_fills_transact_time'), 'fills', ['transact_time'], unique=False)
    op.create_index(op.f('ix_fills_tt_account_id'), 'fills', ['tt_account_id'], unique=False)
    op.create_index(op.f('ix_fills_unique_exec_id'), 'fills', ['unique_exec_id'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('tt_account_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('product_symbol', sa.String(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('tick_value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('net_position', sa.Float(), nullable=False),
    sa.Column('net_open_price', sa.Float(), nullable=False),
    sa.Column('buy_qty', sa.Float(), nullable=False),
    sa.Column('sell_qty', sa.Float(), nullable=False),
    sa.Column('buy_avg_price', sa.Float(), nullable=False),
    sa.Column('sell_avg_price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('sod_position', sa.Float(), nullable=False),
    sa.Column('sod_price', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instrument_id', name='unique_account_instrument')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_account_name'), 'positions', ['account_name'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_instrument_id'), 'positions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_positions_product_symbol'), 'positions', ['product_symbol'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_tt_account_id'), 'positions', ['tt_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_tt_account_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_product_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_instrument_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_name'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_fills_unique_exec_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_tt_account_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_transact_time'), table_name='fills')
    op.drop_index(op.f('ix_fills_trade_date'), table_name='fills')
    op.drop_index(op.f('ix_fills_security_desc'), table_name='fills')
    op.drop_index(op.f('ix_fills_record_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_market_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_instrument_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_exec_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_account_name'), table_name='fills')
    op.drop_index(op.f('ix_fills_account_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_account_product_settings_id'), table_name='account_product_settings')
    op.drop_table('account_product_settings')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_db_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_markets_tt_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_name'), table_name='markets')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_accounts_tt_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
