"""add product_families table

Revision ID: 92b7c71fd4c0
Revises: 12a1fa4d0974
Create Date: 2026-09-01 12:59:40.120264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b7c71fd4c0'
down_revision: Union[str, Sequence[str], None] = '12a1fa4d0974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_families',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('currency_id', sa.String(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_families_symbol'), 'product_families', ['symbol'], unique=False)
    op.create_index(op.f('ix_products_productId'), 'products', ['productId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_productId'), table_name='products')
    op.drop_index(op.f('ix_product_families_symbol'), table_name='product_families')
    op.drop_table('product_families')
    # ### end Alembic commands ###
