"""add fills.row_hash for whole-row duplicate detection

Revision ID: a42525c3cdfd
Revises: 92b7c71fd4c0
Create Date: 2026-09-01 18:09:02.171168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42525c3cdfd'
down_revision: Union[str, Sequence[str], None] = '92b7c71fd4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fills', sa.Column('row_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_fills_row_hash'), 'fills', ['row_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_row_hash'), table_name='fills')
    op.drop_column('fills', 'row_hash')
    # ### end Alembic commands ###
