"""add tick_value_adjusted flag and correct tickValue for known TT unit-scaling bug

Revision ID: f65d8207f6c0
Revises: 31b7f61e3d9c
Create Date: 2026-09-02 21:01:11.655832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65d8207f6c0'
down_revision: Union[str, Sequence[str], None] = '31b7f61e3d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tick_value_adjusted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tick_value_adjusted')
    # ### end Alembic commands ###
